
create table users(
    user_id int primary key generated by default as identity ,
    user_name varchar(255) not null ,
    email varchar(255) not null,
    password varchar(255) not null,
    address varchar(255),
    phone varchar(255)
);

create table devices(
    device_id int primary key ,
    user_id int not null references users(user_id),
    device_name varchar(255),
    device_status varchar(10) default 'offline',
    last_seen timestamp
);

create table sensors
(
    sensor_id   int primary key,
    device_id   int          not null references devices (device_id),
    name        varchar(255) not null,
    sensor_type varchar(50)  not null,
    location    varchar(255) not null,
    ip_address  varchar(50),
    description text,
    created_at  timestamp default now()
);
