--
-- PostgreSQL database dump
--

\restrict FBsi7f8hYWKrQyVOa6r1A2RX59XQwhsubDFwc0traEQnWAhCJ81lqyAhg95dv5Y

-- Dumped from database version 15.17 (Debian 15.17-1.pgdg13+1)
-- Dumped by pg_dump version 15.17 (Debian 15.17-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: devices; Type: TABLE; Schema: public; Owner: dbt5user
--

CREATE TABLE public.devices (
    device_id integer NOT NULL,
    user_id integer,
    device_name character varying(255),
    device_status character varying(10) DEFAULT 'offline'::character varying,
    last_seen timestamp without time zone
);


ALTER TABLE public.devices OWNER TO dbt5user;

--
-- Name: devices_device_id_seq; Type: SEQUENCE; Schema: public; Owner: dbt5user
--

ALTER TABLE public.devices ALTER COLUMN device_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.devices_device_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sensors; Type: TABLE; Schema: public; Owner: dbt5user
--

CREATE TABLE public.sensors (
    sensor_id integer NOT NULL,
    device_id integer NOT NULL,
    sensor_type character varying(50) NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    name text NOT NULL,
    location text,
    ip_address text,
    description text
);


ALTER TABLE public.sensors OWNER TO dbt5user;

--
-- Name: sensors_sensor_id_seq; Type: SEQUENCE; Schema: public; Owner: dbt5user
--

ALTER TABLE public.sensors ALTER COLUMN sensor_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sensors_sensor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: dbt5user
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    user_name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    address character varying(255),
    phone character varying(255)
);


ALTER TABLE public.users OWNER TO dbt5user;

--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: dbt5user
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: devices; Type: TABLE DATA; Schema: public; Owner: dbt5user
--

COPY public.devices (device_id, user_id, device_name, device_status, last_seen) FROM stdin;
1	1	esp32-1	offline	\N
\.


--
-- Data for Name: sensors; Type: TABLE DATA; Schema: public; Owner: dbt5user
--

COPY public.sensors (sensor_id, device_id, sensor_type, created_at, name, location, ip_address, description) FROM stdin;
1	1	Temperature	2026-04-01 17:07:54.179351	Living Room Temperature Sensor	Living Room	192.168.1.21	Monitors ambient temperature near the main sofa
2	1	Motion	2026-04-01 17:07:54.211272	Kitchen Motion Detector	Kitchen	192.168.1.22	Detects movement near the entrance door
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: dbt5user
--

COPY public.users (user_id, user_name, email, password, address, phone) FROM stdin;
1	Marwan Zein	marawnzein222@gmail.com	$2a$11$p5rxV5CcrmZt.iMrybdx0..y9MSxpG2X5vs/ZH1jTaWNPUvXDUEfS	\N	\N
\.


--
-- Name: devices_device_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dbt5user
--

SELECT pg_catalog.setval('public.devices_device_id_seq', 1, true);


--
-- Name: sensors_sensor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dbt5user
--

SELECT pg_catalog.setval('public.sensors_sensor_id_seq', 2, true);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dbt5user
--

SELECT pg_catalog.setval('public.users_user_id_seq', 1, true);


--
-- Name: devices devices_pkey; Type: CONSTRAINT; Schema: public; Owner: dbt5user
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_pkey PRIMARY KEY (device_id);


--
-- Name: sensors sensors_pkey; Type: CONSTRAINT; Schema: public; Owner: dbt5user
--

ALTER TABLE ONLY public.sensors
    ADD CONSTRAINT sensors_pkey PRIMARY KEY (sensor_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: dbt5user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: devices devices_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: dbt5user
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: sensors sensors_device_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: dbt5user
--

ALTER TABLE ONLY public.sensors
    ADD CONSTRAINT sensors_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.devices(device_id);


--
-- PostgreSQL database dump complete
--

\unrestrict FBsi7f8hYWKrQyVOa6r1A2RX59XQwhsubDFwc0traEQnWAhCJ81lqyAhg95dv5Y

