name: Run Backend Tests

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: /home/runner/work/Monitex/Monitex/Backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore smart_home.UnitTests/smart_home.UnitTests.csproj

      - name: Build
        run: dotnet build smart_home.UnitTests/smart_home.UnitTests.csproj --no-restore --configuration Release

      - name: Run tests
        run: dotnet test smart_home.UnitTests/smart_home.UnitTests.csproj --no-build --logger "console;verbosity=detailed" --configuration Release