name: Deploy Angular Static Site

on:
  push:
    branches:
      - master
    paths:
      - "monitex.io/Monitex-frontend/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd monitex.io/Monitex-frontend
          npm install

      - name: Build Angular app
        run: |
          cd monitex.io/Monitex-frontend
          npm run build -- --configuration production --base-href "/monitex.io/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: monitex.io/Monitex-frontend/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
